defmodule OpenResults.SnapshotPayloads do
  @moduledoc """
  Contract-shaped payloads for the ingest and read-back tests.

  `swiss/0` and `keizer/0` are the real fixtures, generated by the
  OpenPairings builder from real tournament data. The registration payload is
  still hand-built from `docs/snapshot-schema.md`, since nothing produces one
  yet.

  No test hard-codes a value that lives inside a payload - a test that needs
  the slug reads it back out of the map it was given. That is what let the
  fixtures drop in without touching a single assertion, and it is what will
  let them be regenerated later without breaking the suite.
  """

  @fixtures Path.expand("../fixtures", __DIR__)

  @doc """
  A swiss tournament, mid-event.

  Round 4 is absent from `rounds` while round 5 is present - the arbiter had
  not published it. That gap is the contract's withholding rule visible in the
  data, and it has to survive storage untouched.
  """
  def swiss, do: load!("snapshot_swiss.json")

  @doc """
  A keizer tournament, whose standings rows carry `value` and `score` instead
  of a positional tiebreak list.
  """
  def keizer, do: load!("snapshot_keizer.json")

  @doc """
  A registration submitted from the public form.
  """
  def registration do
    %{
      "schema" => "openresults/registration",
      "version" => 1,
      "received_at" => "2026-02-01T09:12:00Z",
      "tournament_slug" => "gent-spring-open-2026",
      "player" => %{
        "name" => "De Vos, Ilse",
        "rating" => 1804,
        "federation" => "BEL",
        "fide_id" => 2_503_014,
        "club" => "KGSRL",
        "email" => "ilse@example.invalid",
        "requested_byes" => [3, 4]
      }
    }
  end

  @doc """
  `payload` as a newer OpenPairings would send it.

  Fields this server has never heard of, at the top level, on the tournament,
  on a player, on a board and on a standings row - the five places a future
  version is most likely to grow one. Built by decorating whatever payload it
  is handed, so a regenerated fixture keeps testing the right thing.
  """
  def from_the_future(payload) do
    payload
    |> Map.put("broadcast", %{"lichess" => "abcd1234"})
    |> Map.put("unknown_top_level", "kept anyway")
    |> update_in(["tournament"], &Map.put(&1, "time_control", "90+30"))
    |> update_in(["players", Access.at(0)], &Map.put(&1, "birth_year", 1990))
    |> update_in(
      ["rounds", Access.at(0), "boards", Access.at(0)],
      &Map.put(&1, "move_count", 41)
    )
    |> update_in(["standings", "rows", Access.at(0)], &Map.put(&1, "performance", 2650))
  end

  @doc """
  A payload with a field somewhere inside changed, to force a genuinely new
  row rather than an idempotent repeat.
  """
  def republished(payload) do
    update_in(payload, ["standings", "after_round"], &(&1 + 1))
  end

  @doc """
  Loads a fixture from disk. Read at run time rather than at compile time, so
  a regenerated fixture takes effect without a recompile.
  """
  def load!(name) do
    @fixtures
    |> Path.join(name)
    |> File.read!()
    |> Jason.decode!()
  end
end
