defmodule OpenResults.SnapshotPayloads do
  @moduledoc """
  Contract-shaped payloads for the ingest and read-back tests.

  `swiss/0` and `keizer/0` are the real fixtures, generated by the
  OpenPairings builder from real tournament data. The registration payload is
  still hand-built from `docs/snapshot-schema.md`, since nothing produces one
  yet.

  No test hard-codes a value that lives inside a payload - a test that needs
  the slug reads it back out of the map it was given. That is what let the
  fixtures drop in without touching a single assertion, and it is what will
  let them be regenerated later without breaking the suite.
  """

  @fixtures Path.expand("../fixtures", __DIR__)

  @doc """
  A swiss tournament, mid-event.

  Round 4 is absent from `rounds` while round 5 is present - the arbiter had
  not published it. That gap is the contract's withholding rule visible in the
  data, and it has to survive storage untouched.
  """
  def swiss, do: load!("snapshot_swiss.json")

  @doc """
  A keizer tournament, whose standings rows carry `value` and `score` instead
  of a positional tiebreak list.
  """
  def keizer, do: load!("snapshot_keizer.json")

  @doc """
  A team round robin, four teams, round 1 played with its results public and
  standings published through it - `teams`, `rounds[].matches`,
  `team_standings` and `board_stats` all carry real numbers.
  """
  def team_round_robin, do: load!("snapshot_team_roundrobin.json")

  @doc """
  A team Swiss: five teams of three boards, three rounds, paired team against
  team (C.04.6, OpenPairings 0.62.0 and later), standings published through
  round 3. Every round has its matches, and the five teams make an odd field,
  so each round has a pairing-allocated bye, scored as a drawn match.

  What the fixture exercises on purpose: a reserve who takes board 3 in round
  3 (Antwerp Knights R), a board nobody sat at in round 2 (Charleroi had two
  players, so board 3 of its match with Brugse SK is a forfeit win that is in
  the match's `boards` and score but is not a board on the page), a team with
  a short name, and a captain.

  Built by hand from `docs/snapshot-schema.md` and the shapes OpenPairings'
  builder produces (match points 2/1/0, a bye worth a drawn
  match); the tie-break values are placeholders, since this server only ever
  displays them.
  """
  def team_swiss, do: load!("snapshot_team_swiss.json")

  @doc """
  A team round robin with optional line-ups (OpenPairings since 2026-10-03),
  generated by OpenPairings' `mix pairings.snapshot_fixtures`: three of the
  four teams have no players, so most matches have no board on the page at
  all - their results are only in the matches' `game_points` and the team
  standings. Round 1 has a match decided by its score alone and one against
  empty seats; round 2 a team absent as a team. Two teams carry a
  `teams[].rating`, one of them typed in on OpenPairings' Teams page.
  """
  def team_lineups_optional, do: load!("snapshot_team_lineups_optional.json")

  @doc """
  A team Swiss that has been created and has its teams but has not paired a
  round yet: `team_event` and `teams` are there, there is no round and
  nothing in the standings.
  """
  def team_swiss_unpaired do
    team_swiss()
    |> Map.put("rounds", [])
    |> Map.put("board_stats", [])
    |> put_in(["team_standings", "rows"], [])
    |> put_in(["team_standings", "after_round"], 0)
    |> put_in(["standings", "rows"], [])
    |> put_in(["standings", "after_round"], 0)
  end

  @doc """
  A registration submitted from the public form.
  """
  def registration do
    %{
      "schema" => "openresults/registration",
      "version" => 1,
      "received_at" => "2026-02-01T09:12:00Z",
      "tournament_slug" => "gent-spring-open-2026",
      "player" => %{
        "name" => "De Vos, Ilse",
        "rating" => 1804,
        "federation" => "BEL",
        "fide_id" => 2_503_014,
        "club" => "KGSRL",
        "email" => "ilse@example.invalid",
        "requested_byes" => [3, 4]
      }
    }
  end

  @doc """
  `payload` as a newer OpenPairings would send it.

  Fields this server has never heard of, at the top level, on the tournament,
  on a player, on a board and on a standings row - the five places a future
  version is most likely to grow one. Built by decorating whatever payload it
  is handed, so a regenerated fixture keeps testing the right thing.
  """
  def from_the_future(payload) do
    payload
    |> Map.put("broadcast", %{"lichess" => "abcd1234"})
    |> Map.put("unknown_top_level", "kept anyway")
    |> update_in(["tournament"], &Map.put(&1, "time_control", "90+30"))
    |> update_in(["players", Access.at(0)], &Map.put(&1, "birth_year", 1990))
    |> update_in(
      ["rounds", Access.at(0), "boards", Access.at(0)],
      &Map.put(&1, "move_count", 41)
    )
    |> update_in(["standings", "rows", Access.at(0)], &Map.put(&1, "performance", 2650))
  end

  @doc """
  A payload with a field somewhere inside changed, to force a genuinely new
  row rather than an idempotent repeat.
  """
  def republished(payload) do
    update_in(payload, ["standings", "after_round"], &(&1 + 1))
  end

  @doc """
  Loads a fixture from disk. Read at run time rather than at compile time, so
  a regenerated fixture takes effect without a recompile.
  """
  def load!(name) do
    @fixtures
    |> Path.join(name)
    |> File.read!()
    |> Jason.decode!()
  end
end
