import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :openresults, OpenResultsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :openresults, OpenResultsWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# A production run that does not migrate at boot - `mix phx.server`, which is
# how the service runs - refuses to start on a database that is behind the
# code rather than serving pages that fail. A release migrates at boot and
# never gets as far as asking. See `OpenResults.Application`.
config :openresults, :refuse_pending_migrations, true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
