defmodule OpenResultsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :openresults

  # The hall display's socket (`OpenResultsWeb.HallLive`), the one public
  # page with a connection. Declared WITHOUT the session connect-info on
  # purpose: that option makes LiveView check a CSRF token against a session
  # cookie, and the public side has neither - so every connection would be
  # refused as stale and the page would reload itself forever. Nothing on a
  # public LiveView acts for anyone, so there is nothing for a CSRF check to
  # protect; `check_origin` still keeps other sites' pages off the socket.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: true,
    longpoll: true

  # The piece sprites: third-party art that changes only with a release, and
  # that a round of sixty boards points at sixty times a page. A day's cache
  # (the ETag still revalidates after it) instead of a request per view.
  plug Plug.Static,
    at: "/pieces",
    from: {:openresults, "priv/static/pieces"},
    only: ~w(cburnett.svg chessnut.svg),
    cache_control_for_etags: "public, max-age=86400"

  # The flags (`OpenResultsWeb.Flags`): third-party art, one small file per
  # country, changed only by a release. A month's cache; the ETag still
  # revalidates after it.
  plug Plug.Static,
    at: "/flags",
    from: {:openresults, "priv/static/flags"},
    cache_control_for_etags: "public, max-age=2592000"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :openresults,
    gzip: not code_reloading?,
    only: OpenResultsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :openresults
  end

  plug Plug.RequestId
  # `log: :debug` rather than the default `:info`: the 2026-09-12 load test's
  # own numbers (see docs/load-test-2026-09-12.md) showed this plug's two
  # lines a request ("GET /path", "Sent 200 in Xms") adding real, measured
  # contention once concurrency climbed past a few hundred - Logger writes to
  # its console backend from the request process itself, and that is one
  # more thing competing for the single pinned core alongside every other
  # request. `config/prod.exs` already sets the general Logger level to
  # `:info`, so this line is simply filtered out in production, exactly as it
  # was before this plug started emitting anything - while dev, which never
  # raises the Logger level, keeps seeing every request exactly as before.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: :debug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Counts the bytes read, for the installation-key snapshot cap - see
    # `OpenResultsWeb.BodyReader`. Reads exactly as the default does.
    body_reader: {OpenResultsWeb.BodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  # No `Plug.Session` here any more. It used to be, and every public response
  # stayed cookie-free only because nothing on the public side happened to
  # call `fetch_session`. The one session this app has belongs to `/admin`
  # and is plugged in that pipeline alone - see
  # `OpenResultsWeb.Plugs.AdminSession` - so a public route that tried to
  # use a session would now fail loudly instead of quietly setting a cookie.
  # (The public session options that used to sit at the top of this file
  # went with the hall display's socket, which is declared without them.)
  plug OpenResultsWeb.Router
end
