defmodule OpenResultsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :openresults

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_openresults_key",
    signing_salt: "c8U4zoRG",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :openresults,
    gzip: not code_reloading?,
    only: OpenResultsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :openresults
  end

  plug Plug.RequestId
  # `log: :debug` rather than the default `:info`: the 2026-09-12 load test's
  # own numbers (see docs/load-test-2026-09-12.md) showed this plug's two
  # lines a request ("GET /path", "Sent 200 in Xms") adding real, measured
  # contention once concurrency climbed past a few hundred - Logger writes to
  # its console backend from the request process itself, and that is one
  # more thing competing for the single pinned core alongside every other
  # request. `config/prod.exs` already sets the general Logger level to
  # `:info`, so this line is simply filtered out in production, exactly as it
  # was before this plug started emitting anything - while dev, which never
  # raises the Logger level, keeps seeing every request exactly as before.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: :debug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpenResultsWeb.Router
end
